#!/bin/bash
SPECFILE=$1
REQTYPE=$2

DEBUG=0
tabs 60

function debug {
	if [[ $DEBUG == 1 ]]; then
		echo -e $1
	fi
}



#
#
#
if [ -z $SPECFILE ] || [ -z $REQTYPE ]; then
	echo "[ERROR] usage: define_dependency_v2 PATH_TO_SPECFILE BUILDREQUIRES_OR_REQUIRES"
	exit
fi

while read -r l; do
	arr_require_statement=($l)
	debug "\n------\n$REQTYPE dependency from spec file: ${arr_require_statement[1]}"
	debug "command: dnf provides \"${arr_require_statement[1]}\""
	r_dnf_provides=$(dnf provides ${arr_require_statement[1]})
	NAME_WITH_VERSION=$(echo "$r_dnf_provides" | sed '1d' | sed 's/\s.*$//')
	debug 1
	debug "$NAME_WITH_VERSION"
        NAME=$(./package_name_parser $NAME_WITH_VERSION)
	debug "search ${arr_require_statement[1]}, dnf provides: $NAME"

	rpm_list_foreman="$(cat ./rpm_list_foreman)"
	#echo "$rpm_list_foreman"
	if [ "$rpm_list_foreman" == *"$NAME"* ]; then
		echo -e "Dependency: ${arr_require_statement[1]},\t found $REQTYPE dependency $NAME"
	else
		echo -e "Dependency: ${arr_require_statement[1]},\t dnf provides $NAME doesn't match."
	fi
#	if [[ "$l" == *"$pkg_type"* ]] && [[ "$l" == *"$PKGKEYWORD"* ]]; then
#		exit 0
#	fi
done < <(rpmspec -P $SPECFILE | grep ^$REQTYPE)
