#!/bin/bash
INPUT_FILE=$1
NARROW_PKG_NAME=$2

DEBUG=0
tabs 60

function debug {
	if [[ $DEBUG == 1 ]]; then
		echo -e $1
	fi
}


while read -r l; do

	# Skip if is empty line
	[ -z "$l" ] && continue
	
	NAME_WITH_VERSION=$(echo $l | sed 's/\s.*$//')
	NAME=$(./package_name_parser $NAME_WITH_VERSION)
	debug "\n------\nname=$NAME"

	# Test: limit to the package name want to be tested
	if [ $NAME != $NARROW_PKG_NAME ]; then
		continue
	fi

	DNF_INFO_ARR=($(dnf info $NAME | grep "License      : \|URL          : "))
	#echo ${DNF_INFO_ARR[@]}

	# Skip if can't find package
	if [ "${DNF_INFO_ARR[0]}" == "Error:" ]; then
		continue
	fi

	# TODO: Skip if found more than 2 lines

	URL=${DNF_INFO_ARR[2]}
	debug "url=$URL"
	LICENSE=${DNF_INFO_ARR[@]:5}
	debug "license=$LICENSE"

	echo -e "$NAME\t$LICENSE\t$URL"

done < <(cat $INPUT_FILE)
