#!/bin/bash
INPUT_FILE=$1
NARROW_PKG_NAME=$2

DEBUG=0
tabs 60

function debug {
	if [[ $DEBUG == 1 ]]; then
		echo -e $1
	fi
}


while read -r l; do

	# Skip if is empty line
	[ -z "$l" ] && continue
	
	NAME_WITH_VERSION=$(echo $l | sed 's/\s.*$//')
	NAME=$(./package_name_parser $NAME_WITH_VERSION)
	debug "\n------\nname=$NAME"

	# Test: limit to the package name want to be tested
	if [ ! -z $NARROW_PKG_NAME ] && [ $NAME != $NARROW_PKG_NAME ]; then
		continue
	fi

	DNF_INFO=$(dnf info $NAME)
	debug "dnf_info:"
	debug "$DNF_INFO"

	# Skip if found more than 2 lines
	count=$(echo "$DNF_INFO" | grep -o -i "License      : " | wc -l)
	debug "num_of_results=$count"
	if [ $count -ge 2 ]; then
		echo "package \"$NAME\" is already released by oracle. skipping." 
		continue
	fi

	DNF_INFO_ARR=($(echo "$DNF_INFO" | grep "License      : \|URL          : "))
	debug "${DNF_INFO_ARR[@]}"

	# Skip if can't find package
	if [ "${DNF_INFO_ARR[0]}" == "Error:" ]; then
		continue
	fi


	URL=${DNF_INFO_ARR[2]}
	debug "url=$URL"
	LICENSE=${DNF_INFO_ARR[@]:5}
	debug "license=$LICENSE"

	echo -e "$NAME\t$LICENSE\t$URL"

done < <(cat $INPUT_FILE)
